server.port=3000
spring.application.name=gestionmissions-spring-backend

# MODIFICATION : 'db' est le nom du service MySQL dans ton docker-compose
spring.datasource.url=jdbc:mysql://db:3306/gestion_missions_spring?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Gmail SMTP: utilisez un mot de passe d'application Google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malekkassem80@gmail.com
spring.mail.password=wsawxkoafsikjoyj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8

# Ollama local (Attention : si Ollama tourne sur ton PC, 127.0.0.1 ne marchera pas dans Docker)
# Si tu veux utiliser Ollama depuis Docker, il faut l'URL de ton PC local (ex: http://host.docker.internal:11434)
ollama.base-url=http://host.docker.internal:11434
ollama.model=${OLLAMA_MODEL:mistral}
ollama.timeout-ms=25000

management.endpoints.web.exposure.include=prometheus